services:
  quasar-ssr:
    container_name: quasar_ssr
    image: quasar-ssr:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "39001:39001"
    environment:
      - PORT=39001
    restart: unless-stopped
