version: '3.8'

services:
  web-quasar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quasar-web-rsud
    restart: unless-stopped
    ports:
      - "8124:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_URL_INTERNAL=http://api-webrsud-web
      - API_URL_EXTERNAL=http://localhost:8123
    networks:
      - rsud-network

networks:
  rsud-network:
    external: true
