version: '3.8'

services:
  web-quasar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quasar-web-rsud
    restart: unless-stopped
    ports:
      - "8124:3000" # Tetap buka port 8124 untuk akses langsung (Pintu Darurat)
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_URL_INTERNAL=http://api-webrsud-web
      - API_URL_EXTERNAL=http://localhost:8123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-rsud.rule=Host(`rsud.probolinggokota.go.id`) || Host(`172.20.112.9`)"
      - "traefik.http.routers.web-rsud.entrypoints=web"
      - "traefik.http.services.web-rsud.loadbalancer.server.port=3000"
    networks:
      - rsud-network

networks:
  rsud-network:
    external: true
